### ISSUE TITLE
[Lesson 0] 시작해볼까요?

### ISSUE THREAD

**Issue by kjhg478** [MoZZANG/kimoon-lesson#1]
# [Lesson 0] 시작해볼까요?

레슨을 시작해볼까요 :)

React, TypeScript 기반으로 프로젝트를 시작합니다.
'hello world'를 웹 화면 상에 출력하는 코드를 구현 후, push해주세요.

- 제한조건
  - 본 프로젝트는 웹 서비스이다.
  - 개발 환경은 webpack, typescript를 기본으로 하며, 나머지 환경은 자유롭게 정한다.
  - 배포환경을 구축해야 한다. (aka. CI/CD)
  
그리고 배포환경을 구축하기 전에 CI / CD는 무엇인지 CI / CD를 위해 사용하는 툴은 무엇이고,
각 장단점은 무엇인지 정리해주시면 좋을 것 같아요!

결과적으로 어떤 CI / CD 툴을 사용해서 배포 환경을 구축할 것인지 결정해서 코멘트 남겨주시면 됩니다!

**Comment by MoZZANG** [comment]
Lesson0 완료가 아닐까용?

**Comment by jungwone** [comment]
> Lesson0 완료가 아닐까용?

배포되어 확인할 수 있는 링크 부탁드립니다!

**Comment by jungwone** [comment]
제한사항에 
> 배포환경을 구축해야 한다. (aka. CI/CD)
가 있기 때문에 배포 배포까지 환경을 구성하셔서 링크를 알려주시면 됩니다! 👍

**Comment by MoZZANG** [comment]
https://mozzang.github.io/kimoon-lesson/
이거면 될까요?

**Comment by jungwone** [comment]
고생하셨습니다! 종훈님 코멘트 있으실까요? @kjhg478

**Comment by kjhg478** [comment]
고생하셨습니다~! 저도 코멘트 없습니다!
