### ISSUE TITLE
[Lesson 1] 첫 Pattern

### ISSUE THREAD

**Issue by kjhg478** [MoZZANG/kimoon-lesson#13]
# [Lesson 1] 첫 Pattern

아래와 같이 모양이 화면상에 표시되도록 만들어주세요.
 
```
* 
**
***
****
***** 
```

- 제한조건
  - hello world를 구현한 프로젝트 코드를 수정해서 만든다.
  - view의 구성은 자유롭게 구성한다.

**Comment by MoZZANG** [comment]
음 저는 애초에 react로 만들었는데 
![image](https://user-images.githubusercontent.com/98200337/197972635-d818b642-42eb-46e0-b365-6331f8c480a9.png)

이걸 원하시는건 아니시겠죠? ㅋㅋㅋㅋㅋ

**Comment by jungwone** [comment]
> 

ㅋㅋㅋㅋㅋㅋ 그것도 조건을 만족합니다. view는 구성은 자유롭게 하라고 되어있으니까요🤓
완료되고 배포되면 링크 공유 부탁드립니다!

**Comment by jungwone** [comment]
이슈번호를 커밋에 포함시키지 않으신 것 같습니다! @MoZZANG

**Comment by MoZZANG** [comment]
아이고 이런 ㅠ 제가 내일가서 후딱 이슈번호까지 넣어놓겠슴다!🥲

**Comment by jungwone** [comment]
> 아이고 이런 ㅠ 제가 내일가서 후딱 이슈번호까지 넣어놓겠슴다!🥲

푹쉬세요 기문님😂
이게 pr이랑 이슈랑 번호를 나눠서 쓰는 것 같아요. 그래서 pr이 여러개 만들어졌으면 두번째 이슈라고 하더라도 이슈번호가 #2가 아니더라구여 ㅋㅋㅋ
확인해보니 커밋 제목에 이슈번호가 잘못 들어갔네요! 커밋 메세지만 수정해서 다시 올려주시면 될 것 같습니다! git 연습도 할겸요🤓

**Comment by MoZZANG** [comment]
> 

#13으로 바꾸어 놓았습니다요!

**Comment by kjhg478** [comment]
넵, 다음 커밋때부턴 저 이슈번호 체크해서 커밋해주시면 될 것 같습니다!
중원님 코멘트 있으실까요?!

**Comment by jungwone** [comment]
이번 것은 그냥 넘어갈까 했지만, 수정하신 커밋로그에 별을 찍는게 포함되어 있지 않아서 안타깝지만 넘어갈 수 없게 되었습니다 🥲 @MoZZANG

**Comment by MoZZANG** [comment]
> 이번 것은 그냥 넘어갈까 했지만, 수정하신 커밋로그에 별을 찍는게 포함되어 있지 않아서 안타깝지만 넘어갈 수 없게 되었습니다 🥲 @MoZZANG
> 
> 왜냐하면 커밋 제목은 **make half-triangle with star**인데, 별을 찍는 내용이 담겨있지 않습니다!

https://github.com/MoZZANG/kimoon-lesson/commit/d3a2675e6a38e73d84f28a5f5869282c4dc15492
다시 push 했습니다 허허허

**Comment by kjhg478** [comment]
고생하셨습니다. 저는 코멘트 없습니다.
중원님은 있을까요?

@jungwone

**Comment by jungwone** [comment]
고생하셨습니다! 🚀
