### ISSUE TITLE
[Lesson 2] 사용자가 입력가능하도록 만든다.

### ISSUE THREAD

**Issue by kjhg478** [MoZZANG/kimoon-lesson#14]
# [Lesson 2] 사용자가 입력가능하도록 만든다.

Lesson 1의 프로젝트를 수정하여 사용자가 몇 줄을 찍을 것인지 입력할 수 있도록 한다.

``` 
How many lines? (1..100)  7
*
**
***
****
*****
******
******* 
```

- 제한조건
  - 사용자는 1 부터 100 까지의 정수 값을 입력할 수 있다. 
  - 사용자가 0 이나 마이너스 값을 치는 경우, 문자열(특수문자 포함)을 입력하는 경우에는 경고를 표시하고 input 을 다시 요구한다. 100 보다 큰 경우에도 마찬가지이다.
  - 사용자가 정상 값을 칠 때까지 계속 입력을 받는다.

**Comment by MoZZANG** [comment]
https://mozzang.github.io/kimoon-lesson/

확인한번 부탁드립니다 허허허

**Comment by MoZZANG** [comment]
알람 가나요 중원님?

**Comment by jungwone** [comment]
피드백입니다!

1. 미국에서 왔다고 입력할 경우 영어로 보여주는 것이 꽤 재미있는 발상이라는 생각이 들었습니다 😂

2. prompt
![image](https://user-images.githubusercontent.com/30407259/198190733-a76e398e-9c9a-4448-82f4-e0adc0945870.png)

`prompt`를 사용하신 것 같은데, 이 기능은 일회성이 아니라 여러번 인풋을 바꿔가면서 테스트 할 수 있으면 좋을 것 같습니다. 그런 의미에서 여러분 인풋을 바꿔가면서 테스트하고 싶은데 그때마다 prompt로 새로운 창이 떠서 사용자가 팝업을 보고 숫자를 쓰고 확인 또는 취소를 눌러야 한다면 조금은 번거로울 수도 있지 않을까 하는 생각입니다!
굳이 prompt 창으로 해야만 할까에 대한 고민이 필요해보입니다.

3. prompt에서 취소만 누를경우 다른 prompt가 뜨면서 탈출할 수 없는 지옥이 펼쳐집니다. 유저가 탈출할 수 있는 옵션이 없다는 것이 답답하게 느껴집니다.
4. 어디서 왔냐는 곳에는 어떤 텍스트든 입력하게 되어있는데, 이런 경우에는 보통 어떤 나라들을 선택할 수 있는 옵션을 제시해주는게 더 낫지 않을까요? 
5. 저희 나라 국적의 사람일 경우 한국과 대한민국 두 가지를 입력할 수 있는데, 미국에 대해서는 미합중국, 합중국 등의 선택지는 없고 미국만 통과됩니다.

이제 가장 큰 것 몇 가지를 추가로 피드백 드립니다!
1. 한번 별을 띄우면 서비스를 다시 사용할 수 없다(새로고침을 해야한다).
2. 올바른 숫자를 입력했을 때 `오케이 확인` 이라는 alert를 띄워서 다음 화면으로 확인 버튼을 누르지 않으면 진행되지 못하도록 막아야만 하는 것인지 고민이 필요해 보입니다.
3. 제한사항에서 표시된 패턴은 직각삼각형의 형태인데, 현재 배포된 곳에서 표시되는 모양은 직각삼각형의 형태로 보기가 어렵습니다.
![image](https://user-images.githubusercontent.com/30407259/198191752-1fd98111-79fc-4977-aeae-92e5397e760f.png)

@MoZZANG

**Comment by MoZZANG** [comment]
@jungwone 

피드백 감사합니다.

 > prompt에서 취소만 누를경우 다른 prompt가 뜨면서 탈출할 수 없는 지옥이 펼쳐집니다. 유저가 탈출할 수 있는 옵션이 없다는 것이 답답하게 느껴집니다.
:  사용자가 정상 값을 칠 때까지 계속 입력을 받는다. 는 조건을 반영하려다 보니 정상값을 입력하기 전까지는 탈출불가능하도록 만들었습니다.

나머지 피드백들 그러니까

1. 한번 별을 띄우면 서비스를 다시 사용할 수 없다(새로고침을 해야한다).
2. 올바른 숫자를 입력했을 때 오케이 확인 이라는 alert를 띄워서 다음 화면으로 확인 버튼을 누르지 않으면 진행되지 못하도록 막아야만 하는 것 
   인지 고민이 필요해 보입니다.
3. 제한사항에서 표시된 패턴은 직각삼각형의 형태인데, 현재 배포된 곳에서 표시되는 모양은 직각삼각형의 형태로 보기가 어렵습니다.

등은 기존에 생각했지만 반영하지 않았던 부분인데 좀 더 사용자를 생각해서 반영하도록 하겠습니다!


피드백 주신 내용들을 반영해서 다시 올려보도록 하겠습니다

**Comment by jungwone** [comment]
[코드](https://github.com/MoZZANG/kimoon-lesson/commit/904b051e107e3849c05360946a83bb173c117e45)에드 코멘트 남겼습니다! 
@MoZZANG

**Comment by kjhg478** [comment]
저도 피드백입니다!

중원님이 남겨주신 커밋 코멘트에 대부분 동의해서, 코드 세부사항보단 전체적인 느낌으로 피드백을 드리겠습니다!

먼저 고생하셨습니다!! 참신하고 재밌게 만드시려고 하는 부분이 보이네요!👍

그러나 그전에 레슨의 목적성에 대해 한번 더 생각해주시면 좋지 않을까란 생각이 듭니다! 재밌게 만드는 것도 좋지만 그 재밌게 만든 코드가 레슨과는 너무 동 떨어져 있는 코드라면 기문님도 저희도 그만큼의 시간이 추가로 할애해야 하는 부분이라 이 부분도 같이 생각해주셨으면 좋겠습니다!😂 절대 나쁘다고 말하는건 아닙니다!!

첫 패턴의 코드 구조에서 사용자 입력이 추가되었더니 너무나 많은 조건이 연쇄되어 있는 것을 보고 참신한 발상을 하여 만든 코드가 나중에 하나씩 조건을 추가할때마다 되려 기문님의 발목을 잡지 않을까 걱정이 같이 듭니다!

![image](https://user-images.githubusercontent.com/31474272/198205792-b645b1ef-1ee0-4937-a68c-e824c41da470.png)

그리고 100을 입력했더니 1 부터 100까지의 별이 아닌 맨 윗부분이 저렇게 나오네요! 이 부분도 확인 한번 부탁드리겠습니다!

**Comment by MoZZANG** [comment]
@kjhg478 

제가 이 레슨의 본질을 잊어버리고 있었던 것 같네요 ㅠ 

정말 중요한 말씀을 해주신거 같아서 너무 감사드립니다!

**Comment by MoZZANG** [comment]
@jungwone 

꾸미는데 시간이 너무 드는거 같아서 기능만 넣어서 일단 올렸습니다 ㅠ

https://mozzang.github.io/kimoon-lesson/

**Comment by jungwone** [comment]
색상이 아주 보라보라한게 이쁘네요! 멘트도 재밌군요 ㅎㅎ
저 멘트를 기문님에게 했던 그녀는 누구일까 궁금해지는 오후입니다🤓

커밋 로그를 잠깐 살펴봤는데 이전에 작성하셨던 코드의 대부분이 죽음을 맞이했군요 .. ㅠㅠ 고생하셨습니다. 

이 레슨 프로그램이 쉬운듯 쉽지 않은 부분이 많아서(특히 코멘트랑 피드백이 달리기 시작하면) 조금 힘드실 수도 있지만, 다 끝내셨을 때 하기 전보다 더 성장할 기문님의 모습을 그리며 힘내주셨으면 좋겠습니다 ㅎㅎ

---
자 이제 발견한 버그에 대해서 알려드리겠습니다.
1. 인풋창에 1.2를 입력하고 엔터를 치면 프로그램이 터집니다..!
![image](https://user-images.githubusercontent.com/30407259/198220321-9f4e69a4-c5b2-449e-bf09-a521c8b2ba16.png)

2. 공백과 숫자를 입력하면 통과됩니다(이 부분이 통과되어야 한다고 생각하신다면 솔직하게 말씀해주셔도 됩니다).

3. 숫자와 마침표를 입력하면 통과됩니다.

@MoZZANG

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 

is the 바로 반영해서 올려놓았읍니다. 여유있으실때 봐주십쇼!
https://mozzang.github.io/kimoon-lesson/

**Comment by jungwone** [comment]
일단 이번거는 여기서 마무리 해도 될 것 같습니다! 
추가적으로 말씀드리고 싶은게 있긴한데, 고것들은 다음 이슈에서 다시 얘기해보겠습니다🤓

고생하셨습니다 🚀
