### ISSUE TITLE
[Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by jungwone** [MoZZANG/kimoon-lesson#15]
# [Lesson 3] 새로운 Pattern

아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 사용자가 이해하기 쉽도록 view를 구성한다.
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
https://kimoon-lesson.vercel.app/
이미지 문제때문에 엉엉 너무 늦어버렸습니다 죄송합니다 ㅠㅠ

**Comment by jungwone** [comment]
오 ... ui가 아주 이쁘군요. 
![image](https://user-images.githubusercontent.com/30407259/198916051-2e99d69d-c371-4a4c-8c3d-36577ca8ca93.png)
줄의 위아래 여백은 조금 줄어도 좋을 것 같다는 생각이 드네요!

**Comment by kjhg478** [comment]
혹시 이미지 문제가 왜 일어났는지 알 수 있을까요?

**Comment by jungwone** [comment]
> 혹시 이미지 문제가 왜 일어났는지 알 수 있을까요? 어떤 것 때문에 이미지가 필요했고 문제는 왜 일어났는지 어떻게 해결했는지 알고 싶네요! @MoZZANG
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/31474272/198916477-0973f7e5-fa15-461e-87d3-e68b2cdaca87.png">
> 
> <img alt="image" width="262" src="https://user-images.githubusercontent.com/31474272/198916521-90743820-6f38-44f1-83d9-485edff89cd9.png">
> 
> 그리고 저희가 말했던 모양과 다릅니다!! 이것도 한번 확인 부탁드릴게요!

저도 비슷한 피드백이긴 한데요! 처음에 어떤 모양을 볼지 선택하는 화면에서 패턴을 만드는 함수를 재사용한다면 이미지 파일이 없어도 똑같이 표현할 수 있지 않을까요?

**Comment by jungwone** [comment]
코드에 대한 1차 피드백은 [커밋](https://github.com/MoZZANG/kimoon-lesson/commit/915041270af5ad4862ae1bc9e899bef68dec56c7)에 달아놓았습니다!

**Comment by MoZZANG** [comment]
@kjhg478 
현재 파일구조는 다음과 같습니다
![image](https://user-images.githubusercontent.com/98200337/198917825-a6938578-adb5-477e-92f3-933088dcfbb4.png)

사용자가 패턴을 고르게 하는  PatternChoice.tsx에서 각 패턴모양마다 이미지를 넣어서 예시를 보여주려고 했는데 계속 이미지가 깨져서 안나오더라구요. 그래서 webpack.config.js에 file-loader라는걸 추가해서 build할 때 src > assets에 있는 이미지들도 같이 dist > assets 안에 같이 생성되게 했습니다. 아래처럼요

![image](https://user-images.githubusercontent.com/98200337/198918260-5b05a59f-5f23-4627-8a89-ea6591fcee4c.png)


물론 build되면서 이미지 이름은 랜덤하게 바뀌긴 하는데.. 막상 push 하고 배포해봐도 여전히 그런문제가 생기더라구요. 어제 4시간이나 찾고 해결해보려했는데 안되서 우선 다른방법으로 대체해서 제출했습니다 ㅠㅠ

**Comment by jungwone** [comment]
다이아몬드 패턴에서 `111.`을 입력하면 아래 사진과 같이 alert가 두번 연달아서 뜨게 됩니다.
꼭 두 개를 다 연속적인 alert 창으로 띄워야만 할까에 대한 생각이 드네요!

근데 이것은 그냥 제 생각을 던져보는 것이니 코드에 꼭 반영하시지는 않아도 됩니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/30407259/198918256-789fca47-1742-440d-8e57-bf5cfdc9ee54.png)

![image](https://user-images.githubusercontent.com/30407259/198918284-513d36f3-e451-4e8f-9478-57fbd06fe125.png)

**Comment by jungwone** [comment]
[여기](https://github.com/MoZZANG/kimoon-lesson/commit/e77effd17695eaddccc5e3438fa3b872c87f89be#)도 코멘트요!

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 

https://kimoon-lesson.vercel.app/showStar
피드백 주신부분 모두 반영해서 다시 배포해놓았씁니다!

**Comment by kjhg478** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/31474272/198928757-9736868a-d47c-4c58-94ed-b282001c6dde.png">

다이아몬드 형태인데 짝수를 입력하고 실행을 누르면 이런 alert 창이 나옵니다!

**Comment by kjhg478** [comment]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/31474272/198929386-f26541e8-2bee-4b3c-9adc-96ac7dcad98f.png">

choice, showStar 이 두 페이지에서 새로고침을 하면 이러한 화면이 나옵니다!

**Comment by jungwone** [comment]
![image](https://user-images.githubusercontent.com/30407259/198930257-a6424619-d85d-4a19-a813-eb90cd30c92a.png)

역순형의 이미지가 잘못된 것 같습니다!

**Comment by MoZZANG** [comment]
@kjhg478 
종훈님 제가 진짜 google에 나와았는 이 방법 저 방법 다 해봤는데 다 안되네요 ㅠㅠ 

혹시 같은 문제를 해결하신 전례가 있으신가요?ㅠ

**Comment by jungwone** [comment]
분명히 같은 문제를 겪었던 사람들이 있을겁니다! `rewrites` 말고 다른 명령어도 있고요!
이 문제를 해결하지 못해서 배포 플랫폼을 바꾸기에는 조금 아쉽고요, 분명히 해결하실 수 있을겁니다👍

**Comment by jungwone** [comment]
요런 [블로그](https://medium.com/today-i-solved/deploy-spa-with-react-router-to-vercel-d10a6b2bfde8)의 글도 있는데 이 방법도 시도 해보셨나요? @MoZZANG

**Comment by kjhg478** [comment]
중원님의 해결 방법이 안되면 [링크](https://stackoverflow.com/questions/64815012/why-does-react-router-not-works-at-vercel) 이 방법도 시도해보시길 권장합니다!

**Comment by jungwone** [comment]
![image](https://user-images.githubusercontent.com/30407259/198947015-5c6c098e-0069-4ecf-94f5-1f7a95c71267.png)
이전패턴을 2개까지 기록하고 인풋을 0으로 바꾸고 다른 패턴으로 바꾸면 이전 패턴 하나가 사라져버립니다! 
그리고 현재 패턴은 css가 깨집니다!

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
코멘트 정말 감사합니다. 이미 다 진행해본 방법이지만..ㅠ 엉엉

**Comment by jungwone** [comment]
아시겠지만 각 배포 플랫폼마다 해결 방법이 조금씩 다를거예요. 하지만 아마 문제가 발생하는 원인은 동일할겁니다 spa의 문제니까요!
이 문제가 발생하는 원인에 대해서는 파악하고 계신 상태인가요? @MoZZANG

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 

https://kimoon-lesson.vercel.app/
root = 뿌리 = 김기문 ㅂㅅ

**Comment by jungwone** [comment]
숫자를 잘못 입력하면 인풋이 지워지면서 이전에 출력했던 패턴까지도 사라져버리는 것에 있어서 살짝 갸우뚱 모먼트가 있긴 하지만 일단 클로즈 해도 좋을 것 같습니다!

고생하셨습니다 🚀

**Comment by kjhg478** [comment]
오! 새로고침 부분도 해결 하셨네요! 정말 고생많으셨습니다! 
많이 리서치도 하시고 고생하셨던 것 같은데 어떻게 해결 하셨는지 너무 궁금하네요. 
공유 해주실 수 있을까요?!

마무리 된 이슈에 이렇게 코멘트를 달아서 죄송합니다!!
@MoZZANG

**Comment by MoZZANG** [comment]
@kjhg478 @jungwone 
정말 다양한 방법으로 해봤지만 결국은 등잔밑이 어두웠더라구요 ㅠㅠ
저의 짧디 짧은 cs지식때문에 해결하지 못하고 있었던 것인데, 분명 해결 방법중에 vercel.json을 만들고 안에 아래와 같이 rewrites를 넣어서 최종적으로 자신의 프로젝트의 root에 넣으라고 해결책에서는 얘기해주었습니다.

근데 저는 root가 계속 src라고 생각하고 있어서 src > vercel.json 으로 계속 하다보니 적용이 안된 것이었습니다 ㅠ

그 와중에 갓중원님께서 root가 어딘지 알려주셔서 root로 파일을 옮기고 다시 배포하니 해결되었습니다 ㅠㅠ

![image](https://user-images.githubusercontent.com/98200337/199137696-848f7c86-f388-4f3d-8f4d-91957c8f97ee.png)
