### ISSUE TITLE
[Lesson 4] 이전 패턴 기록 및 Pattern 추가

### ISSUE THREAD

**Issue by jungwone** [MoZZANG/kimoon-lesson#36]
# [Lesson 4] 이전 패턴 기록 및 Pattern 추가 

1. 한번 출력된 이전 패턴 1개가 기록되어 보여야 한다.
    - 이전에 출력된 패턴을 보기 위함이다.
2. 아울러, 아래의 Pattern 을 추가한다. 

```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

- 제한사항
  - 사용자가 이해하기 쉬운 화면과 사용성을 고민한다.

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
https://kimoon-lesson.vercel.app/

설마 아니겠..죠? 갑자기 쌔한 느낌이 들었는데..

**Comment by jungwone** [comment]
고생하셨습니다! 몇 가지 피드백이 있는데요~!

>1. 한번 출력된 이전 패턴 1개가 기록되어 보여야 한다.
1. 제시된 조건과 다르게 하나의 패턴을 선택하고 다른 패턴을 선택하면 이전에 출력했던 패턴이 보이지 않습니다!
- 같은 패턴 안에서만 이전 패턴이 유지됩니다. 구현을 위해서는 ui의 변경이 필요할지도 모르겠습니다. 현재 구조는 빠르게 다른 패턴을 선택하기에도 힘든 구조니까요(무조건 페이지를 이동해야 함)

2. 이전 패턴이 쌓여있지 않음에도 이전 패턴이 출력되고 있습니다.
이전 패턴을 좌우로 나열하셨는데,
![image](https://user-images.githubusercontent.com/30407259/199158922-e1e3c90b-3b83-4272-bcbf-3108921d493e.png)
이런 경우 **현재 별**이 오른쪽으로 밀려 **이전 별**을 메인으로 보여주는 것 같은 느낌이 듭니다. 

3. 라인을 입력한 후 꼭 인풋을 초기화 시켜야만 하는지 의문이 드는데 어떻게 생각하시나요?!
- 몇개의 라인을 보여주고 있는지 확인하려면 무조건 세어봐야만 하니까요.

@MoZZANG

**Comment by jungwone** [comment]
[코드](https://github.com/MoZZANG/kimoon-lesson/commit/f21550fc85db9be2201e919ffc4f6f42648317d4#)에도 코멘트 남겼습니다! @MoZZANG

**Comment by jungwone** [comment]
그리고 [App](https://github.com/MoZZANG/kimoon-lesson/blob/main/src/PatternChoice.tsx)에서 오브젝트 변수를 뿌려주기 위해서 `dangerouslySetInnerHTML`을 사용하셨는데, 이 방식은 [공식문서](https://ko.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)에도 나와있듯이 innterHTML을 써야만 하는 경우에 사용하는 것이 일반적인 것 같습니다.
![image](https://user-images.githubusercontent.com/30407259/199171938-4aa3c84f-f93d-46b2-97ed-f667557f607c.png)

이름부터 위험한(?) 이것을 단지 json 데이터를 보여주기 위해서 사용하는 것은 당위성이 조금 부족하다는 생각입니다!

**Comment by kjhg478** [comment]
허허 중원님께서 피드백을 많이 남겨주셨네요! 

저도 중원님께서 남겨주신 피드백과 거의 비슷한 피드백이기에 수정된 커밋을 올리시면 그 때 다시 한번 보도록 하겠습니다!

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
https://kimoon-lesson.vercel.app/

배포했습니다! 시간나실때 한번 봐주십쇼!

**Comment by kjhg478** [comment]
ui가 많이 바뀌었네요! 고생하셨습니다!

중원님이 먼저 남겨주셨던 피드백의 연장선이긴 한데요.

- input값을 입력하고 별별을 클릭하면 input값이 초기화 됩니다. 패턴을 바꿀때마다 계속해서 input을 입력해줘야 하는데 초기화를 시키지 않는 방안은 어떠신가요?

@MoZZANG

**Comment by MoZZANG** [comment]
@kjhg478 @jungwone 

1. dangerouslySetInnerHTML 에 대해 찾아보았습니다.
사용을 자제해야 하는 가장 중요한 이유는 다음과 같다는 것을 알았습니다.

사이트 간 스크립팅 공격 과 크로스 사이트 스크립팅 (XSS, cross-site scripting)
웹 애플리케이션의 취약점 중 하나 관리자가 아닌 이가 페이지에 악성 스크립트를 삽입할 수 있는 취약점 악성 스크립트를 통해 사용자의 정보(쿠키, 세션등)를 탈취하거나 비정상적인 기능을 수행 주로 다른 웹 사이트와 정보를 교환하는 식으로 작동하므로 사이트 간 스크립팅이라고 함
취약점을 방지하기 위해서는 사용자의 입력 값을 검사하고 사용해야함

따라서 다음 lesson에서 기회가 된다면 다른 방법으로 대체해볼까 합니다. 좋은 공부가 되었습니다.


2. input값을 입력하고 별별을 클릭하면 input값이 초기화 됩니다. 패턴을 바꿀때마다 계속해서 input을 입력해줘야 하는데 초기화를 시키지 않는 방안은 어떠신가요?
 : 에 대해서는 정답은 없다고 생각합니다. 분명 중원님과 종훈님이 말씀하신 방법대로 한다면 동일한 값을 연속적으로 입력하기는 편하다는 장점이 있지만 연속적으로 다른값을 입력하려고 한다면 계속 지웠다 썼다르 반복해야 하는 단점이 있다고 생각합니다.

만일 내가 사용자라면 어떨까 라는 입장으로 사용해보았는데 
우선 같은 패턴내에서 별을 생성한다고 생각해보면 5라는 숫자를 한번 입력하고 계속 enter를 누르게 된다면 이전 별과 현재 별이 어차피 같은 모양이므로 의미가 없다고 생각합니다. 따라서 동일한 5라는 숫자로 패턴을 바꾸어 가며 별을 생성할 것이라는 행동을 기대해볼 수 있다고 생각합니다.

그렇다면 패턴을 바꾸는 행동이 필수적인데 이 행동에는 마우스로 다른 패턴을 클릭하는 행동이 필수불가결합니다. 따라서 다른 패턴선택은 논외로 하고 값을 초기화 시키지 않는다면 사용자는 기존값을 지우는 행동을 추가로 해주어야 하므로 초기화 시키지 않게된다면 기존값을 지우는 행동이 추가로 필요한 것입니다. 따라서 기존값을 초기화시키고 focus를 해주어 신속하고 연속적으로 값을 변경할 수 있게 만드는게 좋겠다고 생각하여 현재와 같이 만들었습니다.

저와 다른 생각이 있다면 언제든지 알려주시면 너무 좋을 것 같습니다!

**Comment by kjhg478** [comment]
고생하셨습니다! 
앞으로도 각 피드백의 대해서 기문님이 어떤 의도를 가지고 개발을 하셨는지 자유롭게 의견을 얘기해주시면 좋을 것 같아요!

다음 레슨은 윤학님이 레슨 4번이 끝나야 진행할 수 있을 것 같습니다. 두 분이 레슨 4번까지 끝나야 진행할 수 있는거라서요!
그래서 내일 중원님의 새로운 의견도 들어보고 윤학님이 4번까지 끝낼 동안 기문님이 다음 레슨에 반영하고 싶다고 한 것들에 대해서 해보고 계시면 어떨까요?!

**Comment by MoZZANG** [comment]
아하! 알겠습니다! 
말씀하신대로 피드백 주신부분 반영해보도록 하겠습니다!

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
어제 종훈님이 주신 피드백과 중원님이 주신 피드백(dangerouslySetInnerHTML 제거 => 이미지로 대체함)해서 다시 배포하였습니다!

https://kimoon-lesson.vercel.app/

**Comment by jungwone** [comment]
> @kjhg478 @jungwone
> 
> 1. dangerouslySetInnerHTML 에 대해 찾아보았습니다.
>    사용을 자제해야 하는 가장 중요한 이유는 다음과 같다는 것을 알았습니다.
> 
> 사이트 간 스크립팅 공격 과 크로스 사이트 스크립팅 (XSS, cross-site scripting) 웹 애플리케이션의 취약점 중 하나 관리자가 아닌 이가 페이지에 악성 스크립트를 삽입할 수 있는 취약점 악성 스크립트를 통해 사용자의 정보(쿠키, 세션등)를 탈취하거나 비정상적인 기능을 수행 주로 다른 웹 사이트와 정보를 교환하는 식으로 작동하므로 사이트 간 스크립팅이라고 함 취약점을 방지하기 위해서는 사용자의 입력 값을 검사하고 사용해야함
> 
> 따라서 다음 lesson에서 기회가 된다면 다른 방법으로 대체해볼까 합니다. 좋은 공부가 되었습니다.
> 
> 2. input값을 입력하고 별별을 클릭하면 input값이 초기화 됩니다. 패턴을 바꿀때마다 계속해서 input을 입력해줘야 하는데 초기화를 시키지 않는 방안은 어떠신가요?
>    : 에 대해서는 정답은 없다고 생각합니다. 분명 중원님과 종훈님이 말씀하신 방법대로 한다면 동일한 값을 연속적으로 입력하기는 편하다는 장점이 있지만 연속적으로 다른값을 입력하려고 한다면 계속 지웠다 썼다르 반복해야 하는 단점이 있다고 생각합니다.
> 
> 만일 내가 사용자라면 어떨까 라는 입장으로 사용해보았는데 우선 같은 패턴내에서 별을 생성한다고 생각해보면 5라는 숫자를 한번 입력하고 계속 enter를 누르게 된다면 이전 별과 현재 별이 어차피 같은 모양이므로 의미가 없다고 생각합니다. 따라서 동일한 5라는 숫자로 패턴을 바꾸어 가며 별을 생성할 것이라는 행동을 기대해볼 수 있다고 생각합니다.
> 
> 그렇다면 패턴을 바꾸는 행동이 필수적인데 이 행동에는 마우스로 다른 패턴을 클릭하는 행동이 필수불가결합니다. 따라서 다른 패턴선택은 논외로 하고 값을 초기화 시키지 않는다면 사용자는 기존값을 지우는 행동을 추가로 해주어야 하므로 초기화 시키지 않게된다면 기존값을 지우는 행동이 추가로 필요한 것입니다. 따라서 기존값을 초기화시키고 focus를 해주어 신속하고 연속적으로 값을 변경할 수 있게 만드는게 좋겠다고 생각하여 현재와 같이 만들었습니다.
> 
> 3. 이전 별이 없다면 0개라고 화면을 잡아먹는 것 보단 이전 별이 있을 때 출력해주는 방안은 어떠신가요?! (중원님의 2번 피드백과 동일합니다!)
>    : 좋은 생각인거 같습니다! 다음 lesson에 반영할 기회가 있다면 반영해도록 하겠습니다!
> 
> 저와 다른 생각이 있다면 언제든지 알려주시면 너무 좋을 것 같습니다!

굉장히 잘 조사해주셨네요!! 고생하셨습니다 :)

코드에 대한 피드백은 [https://github.com/MoZZANG/kimoon-lesson/commit/58340af601ae614e1435f4d9c6ad2844c92d1d47](여기)에 달아두었습니다.

**Comment by kjhg478** [comment]
고생하셨습니다! 이슈는 마무리 하도록 하겠습니다!
