### ISSUE TITLE
[Lesson 5] 다른 사람의 코드를 리뷰하기

### ISSUE THREAD

**Issue by kjhg478** [MoZZANG/kimoon-lesson#40]
# [Lesson 5] 다른 사람의 코드를 리뷰하기

다른 사람의 코드를 한번 리뷰해봅시다.
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.

이 코드를 봐주시면 됩니다. ㅎㅎ 절대 좋은 코드는 아니에요
https://github.com/jungwone/jungwone-lesson-diff
https://github.com/kjhg478/someone-lesson-5

각 레포에 초대해드렸습니다!

**Comment by MoZZANG** [comment]
느낀점이 있을 때마다 코멘트를 추가해서 남기도록 하겠습니다. 제가 다 정리해서 한번에 올릴 자신이 없어서 ㅋㅋㅋㅋㅋ

우선 
![image](https://user-images.githubusercontent.com/98200337/199633723-7ff13c54-744a-4b77-9dca-e3e7f9b01e7b.png)

input에 onChange이벤트를 걸어놓으셔서 사용자가 입력할때마다 onChange이벤트가 발생하네요 change이벤트 함수인 handleChangeInput안에서 setInput이 무조건 실행되게 되어 있고 땨뮨애 사용자가 입력한 값으로 state가 실시간으로 바뀌기 때문에 사용자가 한글자씩 입력할 때마다

![image](https://user-images.githubusercontent.com/98200337/199634026-972d612b-c053-4402-8faa-92536840fc47.png)
 
부모컴포넌트인 App이 리렌더링이 되고 있습니다. 다행히 자식컴포넌트인 Radio는 memo를 해두셔서 리렌더링이 안되고 있네요

만약 App컴포넌트 코드가 많아진다면 성능에 영향이 있을 수 있지 않을까라는 생각을 해봅니다. 이런 경우에는 input태그에 useRef를 걸어서 값 변화를 읽는다면 리렌더링이  실시간으로 되지는 않지만 값변화는 실시간으로 읽어올 수 있다고 알고 있습니다 허허허

또 다른 느낀점을 찾으러 가보겠습니다!

**Comment by MoZZANG** [comment]
input창에서 사용자가 값을 입력하고 엔터를 누르면 중원님은 값이 초기화 되지 않게 해두셨군요!

제 lesson에 코멘트로 그 부분에 대해 제 생각을 남겨두었습니다만 역시 저는 초기화 해주지 않으면 연속해서 값을 빠르게 입력할 수 없고 다른 값을 원한다면 지우고 다시 입력해야하는 점이 조금은 불편하게 느껴지는 점도 있습니다 호호호

**Comment by MoZZANG** [comment]
현재 직각삼각형에서 패턴을 생성한 다음 다른 패턴을 클릭하면 그 패턴에 맞는 모양으로 변하고 있습니다. 이는 저도 직면했던 문제인데 저는 이것이 뭔가 정상적인 작동이 아니라고 생각이 들어 그런 작동방식을 차단하는 쪽으로 코드를 짰습니다.

혹시 중원님은 다른패턴을 선택할 때마다 현재 패턴이 변화되게 만드신 이유가 있으실까용?

**Comment by jungwone** [comment]
> 

App 컴포넌트에 state가 존재하기 때문에 말씀하신대로 state가 변한다면 App이 리렌더링 되는게 당연하겠죠. 그래서 App의 자식 컴포넌트들이 리렌더링 되지 않도록 최적화를 진행한 것이구요!
setInput이 onChange이벤트가 발생할 때마다 실행하게 한 것은 의도된 것이라고 봐주시면 될 것 같습니다. 사용자가 값을 입력하는 자율성까지는 막고 싶지 않았기 때문에요.

**Comment by jungwone** [comment]
> 

같은 라인 수를 기반으로 다른 패턴을 테스트하는 케이스도 존재하기 때문에 저렇게 두었습니다.  패턴을 쭉쭉 바꿔나가면서 볼 수 없고, 패턴을 바꿀때마다 값을 입력해야 한다면 그것대로 불편할 수 있겠죠.

그리고 초기화 하지 않은 또 하나의 이유는, 실제로 입력된 값을 초기화 하는 케이스가 많지는 않으니까요 채팅 시스템이 아니라면요. 
예를 들어 쿠팡의 상품 검색, 네이버, 구글 등에서 키워드 검색 등을 봐도 값을  초기화 시키지는 않지용 @MoZZANG

**Comment by jungwone** [comment]
> 

다른 패턴을 클릭할 때 그에 맞는 패턴으로 바뀐다면 당연히 패턴이 새로 기록된 것이기에 이전 패턴도 변화해야하는게 맞겠죠?

음 다른 패턴을 선택했을 때 현재 패턴이 바뀌지 않는 것이 저는 조금 더 자연스럽지 못한 방식이라고 생각했습니다.
![image](https://user-images.githubusercontent.com/30407259/199636282-aa126b21-af15-4410-abbe-a6fd04a32690.png)
이런 경우에도 체크만 하면 바로 결과가 반영되니까요.

말씀하신 비교 케이스에 대해서는 이해가 잘 안되는데 조금 더 상세하게 설명해주시면 좋을 것 같습니다! @MoZZANG

**Comment by jungwone** [comment]
질문이 있으시다면 더 답변해드릴 수 있지만 기본적으로 이번 레슨은 
>다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
>다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.

이기 때문에 코드에 대한 리뷰가 더 맞는 방향성입니당 @MoZZANG

**Comment by kjhg478** [comment]
조금 더 첨언드리자면 저 부분도 느낀점 맞습니다! 
그러나 기문님이 말씀하시는 부분은 코드를 분석하고 사용성과 기능성을 테스트하는데 더 가깝다고 봐요.

저희가 생각하는 이번 레슨의 방향은 다른 사람의 코드를 보고 어떤 부분이 좋았는지 나는 이 패턴을 만들기 위해 이러한 방식으로 코드를 짰는데 이런 방식으로도 짤 수 있구나라는 여러 방법에 대해서 생각해보는 계기를 심어주고 싶었습니다!

**Comment by MoZZANG** [comment]
@jungwone
중원님 궁금한 점이 있습니다!

 중원님은 styled component보다는 module.css로 className을 사용하셔서 스타일링을 해주셨는데 어떤 이유가 있으신건가요? 
절대 뭐가 좋고 나쁘고 옳고 그른건 없으니 순수하게 궁금해서 여쭈어 봅니다! 😆

**Comment by jungwone** [comment]
1. 번들 사이즈를 계속 작게 유지하고 싶었습니다 ㅋㅋ styled components 는 unpacked size가 3메가 넘으니까요. 작은 규모의 프로젝트다 보니까 계속 프로젝트를 가볍게 끌고가고 싶었던 점이 있었습니다.

2. 별도의 스타일링 라이브러리를 사용하지 않아도 이 정도 규모의 프로젝트에는 생산성에 크게 무리가 없을 것이라고 판단했습니다.
 => 그리고 css module을 사용하면 클래스명이 겹쳐서 css가 충돌날 일도 없으니까요!

3.컴포넌트 자체의 수가 별로 많지 않음(컴포넌트와 강하게 결합될만한 css가 거의 없음)
 => 추후에 규모가 커지고 스타일을 컨트롤 하는 부분이 복잡해진다면 CSS in JS를 고려해볼 수도 있겠네요!

@MoZZANG

**Comment by jungwone** [comment]
원하신다면 1번을 조금 더 쓰셔도 되고요, 아니면 2번 써주시면 될 것 같습니다 :D

**Comment by MoZZANG** [comment]
@jungwone 

<중원님의 코드를 보고 '좋았던 점' 과 '느낀 점'>

우선 소~~~~올직히 많이 놀랐습니다. 좋은쪽으로요😆 

1. valid check를 위한 함수를 많이 사용한 점을 보고 놀랐습니다. 이런 방식으로도 생각해볼 수가 있구나 라고.
   저는 그냥 하나의 함수에 모든 valid check를 위한 코드를 다 때려박았는데 이렇게 하면 특정 valid check를 하기 위해서는 재사용이 불가능 한거 같습니다. 반면에 중원님 처럼 다양한 valid check를 함수형태로 만들어 놓으니 가독성과 재사용성에서 좋다고 느꼈습니다.

2. 패턴찍기에서 특히 다이아몬드나 기울어진 삼각형과 같은 패턴을 찍기위해 많은 고심을 했었는데 중원님의 코드에서 pre 태그를 보고 무릎을 탁 쳤습니다. pre 태그를 사용함으로써 

 - <pre>태그는 미리 정의된 형식의 텍스트를 정의할 때 사용한다.
- 또한 텍스트에 사용된 여백과 줄바꿈이 모두 그대로 브라우저 화면에 나타난다.

와 같은 효과를 통해 공백 문제를 해결할 수 있다는 것을 배웠습니다.

3. 폴더구조(?)에 대해 배울 수 있었던 것 같아서 좋았습니다. 
  1) constants라는 폴더를 만들고 안에 pattern들을 모아서 마치 하나의 component처럼 export해서 사용할 수 있는점.
  2)  types라는 폴더안에 여러 타입을 지정해서 export해서 사용할 수 있는 점.
  3) Java나 Spring 이후로 utils 폴더를 만들고 안에 util기능하는 것들을 모아두는 것도 처음 봐서 신선하고 좋았습니다.
 

갯수로 치자면 훨씬 더 많지만 저의 식견으로는 이 정도가 코멘트로 남길 수 있는 부분이 아닐까 싶습니다!
  
정말 많이 보고 배웠습니다.  ㅅ...사..ㄹ 아닙니다 중원닙 감사합니다

**Comment by MoZZANG** [comment]
@kjhg478 

<종훈님의 코드를 보고  '좋았던 점' & '느낀 점'>

1. webpack 설정을 mode별로 분리할 수도 있구나라는 걸 알게되었고 인상깊었습니다.

2. custom hook을 이용해서 이전 패턴을 보여주는 부분. 오 이렇게도 할 수 있겠구나 라는 생각이 들었고 
3. 패턴을 만들어주는 함수와 input valid 체크하는 함수를 utils 폴더로 빼서 재사용이 가능하고 유지보수가 쉽게 만드신 부분도 새롭게 배울 
    수 있었습니다.
4. 중원님과 마찬가지로 pre태그를 사용하셨군요. 덕분에 pre 태그에 대해 알게되고 공부할 수 있는 기회가 되어서 좋았습니다!

좋훈님 코드도 더 많은 좋은점 느낀점이 있지만 큰 것 위주로 남겼습니다. 

정말 많은 공부가 되었습니다 감사합니다!

**Comment by jungwone** [comment]
종훈님이 퇴근을 하셨네요! ㅋㅋ 작성하느라 고생하셨습니다.
1번이랑 어느정도 겹치는 부분도 있을텐데, 2번 간략하게나마 적어주시면 이슈 클로즈 해도 될 것 같네요 :)

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 

아차차 2번에 대해 리뷰를 남기는걸 깜빡했군요 ㅋㅋㅋ

우선 가장 크게 와닿는 부분은 제가 알던 세상은 정말 작은 세상이라는 것을 알게되었습니다.

중원님과 종훈님의 코드를 보면서 단순히 동작하게만 코드를 짜는 것이 아닌 어떻게 하면 좀 더 좋게 코드를 짤 수 있을까를 고민해봐야 함을 느꼈습니다. 유지보수, 가독성, 성능 최적화 등까지 생각하면서 코드를 짜는 것이 쉽지 않은 부분이고 앞으로 해야할 숙제 중 하나라고 생각이 듭니다.

또한 웹팩설정과  타입스크립트를 찍먹 해볼 수 있는 시간이었는데요. 타입스크립트는 솔직히 아직까지는 왜 더 좋은지는 알만큼 찍어먹어보지 못해서 잘 모르겠습니다 ㅋㅋㅋㅋㅋ 하지만 좋은 시작점이었던 것은 분명하다고 생각합니다.

두분이서 너무 고생많으셨고 정말 감사합니다.

중원님은 가시지만 종훈님, 앞으로 많이 배우겠습니다!🤩

**Comment by jungwone** [comment]
기문님이 많은 것을 얻어가실 수 있는 시간이 되었으면 좋겠네요 :)

말씀하신대로 그런 고민들이 저희를 성장하게 해주는 것 같아요. 좋은 코드도 그만큼 많이 찾아보고 계속 공부하게 되더라구요.

타입스크립트의 장점을 아직 잘 누리지 못하고 계실 수도 있다는 생각이 들긴 드네요 ㅎㅎ. 다음 레슨에서 그 부분에 대한 피드백을 드려보겠습니다!

고생하셨습니다. 다음 이슈로 가죠!
