### ISSUE TITLE
[Lesson 6] 시작, 종료 기능 만들기

### ISSUE THREAD

**Issue by jungwone** [MoZZANG/kimoon-lesson#41]
# [Lesson 6] 시작, 종료 기능 만들기

시작, 종료 기능을 추가한다. 종료시엔 입력부가 사라지며, 기존에 출력한 패턴은 그대로 남긴다. 시작시 기존 기록된 패턴을 모두 초기화한다.

- 제한사항
  - git에서 'develop' branch로 분리하여 개발을 진행한다.

**Comment by jungwone** [comment]
금방 해주셨군요! 질문 사항이 있는데요!

![image](https://user-images.githubusercontent.com/30407259/199905206-8f34b5d1-0d89-497e-b305-7dbed4dd5d43.png)

처음에 패턴을 선택하지 않으면 인풋창이 클릭되지 않는데, 이는 의도된 동작인가요?
만약 의도된 동작이라면 패턴을 선택하라는 알림을 띄워줘도 좋을 것 같네용. @MoZZANG

**Comment by kjhg478** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/31474272/199905307-74ecf0d4-9df6-4612-94f0-3fccefa51ca7.png">

종료를 했다가 시작하기를 누르면 이전 패턴이 그대로 남아있네요!
제한사항 - 시작시 기존 기록된 패턴을 모두 초기화 해주셔야 합니다!

**Comment by MoZZANG** [comment]
@jungwone 
의도된 것이고 별별이라는 버튼을 누르면 알림창을 띄워주는데 사용자가 별별 버튼을 눌러보지 않으면 모르니 렉이라고 생각할 수도 있겠네요

**Comment by MoZZANG** [comment]
@kjhg478 
에고고 바로 수정해서 올리도록 하겠슴다. 번거롭게 해드려 죄송해요

**Comment by kjhg478** [comment]
아! 절대 죄송할 필요는 없습니다!! 당연히 실수는 발생할 수 있는 부분이라서요. 번거롭지 않습니다!

추가로 하나 더 피드백 드리면 오빠 별 보러 갈래? 라는 버튼이 시작하기의 느낌을 주는데 페이지를 이동하면 다시 시작하기를  눌러야 input창이 나옵니다. 사용자 입장에서는 약간 혼동을 줄 수 있을 것 같은데 어떻게 생각하시나요? 당연히 큰 불편함은 아니지만요!

**Comment by jungwone** [comment]
[코멘트](https://github.com/MoZZANG/kimoon-lesson/commit/92018cded98e373a828ba9082e31632292b7aa65#) 남겼습니당

**Comment by MoZZANG** [comment]
@kjhg478 
분명 다른 사용자 입장에서는 그런 혼동을 줄 수 있겠군요.
저는 뭔가 게임 인트로처럼 사용하고 싶어서 없애기는 아깝다는 마음이 들어 멘트를 조금 수정하는 방향으로 해보겠습니다!

**Comment by kjhg478** [comment]
[코멘트](https://github.com/MoZZANG/kimoon-lesson/commit/92018cded98e373a828ba9082e31632292b7aa65#r88842847) 저도 하나 남겼습니다~!

**Comment by MoZZANG** [comment]
@jungwone @kjhg478 
https://kimoon-lesson.vercel.app/

수정해서 올렸습니다

**Comment by kjhg478** [comment]
음! 저의 피드백은 오빠랑 별보러가기와 시작하기 두번 버튼을 누르는 것의 대한 약간의 불편함 및 혼동을 얘기했던 것이긴 했는데 게임 인트로 버튼처럼 사용하고 싶기에 없애기는 아깝다라는 답변을 주신거죠?!

@MoZZANG

**Comment by MoZZANG** [comment]
@kjhg478 
맞습니다! 뭔가 인트로 느낌을 원해서 지우기는 아깝네요 ㅠ

**Comment by kjhg478** [comment]
네, 알겠습니다~ 
그러면 브런치 develop에서 개발한 내용을 master로 배포된 것처럼 dev용도의 배포 버전도 만들어주면 좋을 것 같습니다! dev에 반영된 것을 확인 할 수 있는 용도로요!

**Comment by MoZZANG** [comment]
@kjhg478 
dev용 - https://kimoon-lesson-dev.vercel.app/
master용 - https://kimoon-lesson-main.vercel.app/

**Comment by kjhg478** [comment]
고생하셨습니다!
오늘 플래닝 일정 이후에 레슨을 바로 더 진행할 지 나중에 진행할 지 나올 것 같네요!

이번 이슈는 마무리 하겠습니다!

**Comment by jungwone** [comment]
고생하셨습니다 ㅎㅎ
